services:
  - type: web
    name: assessor-api
    runtime: python
    region: singapore
    plan: free
    branch: main
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - fromGroup: insightqa-env-group
